[package]
name = "writium-framework"
version = "0.1.0"
authors = ["PENGUINLIONG <admin@penguinliong.moe>"]
description = "Static article host based on iron."
license = "MIT"
repository = "https://github.com/PENGUINLIONG/writium"

[dependencies]
hyper = "0.11"
log = "0.3"
url = "*"
serde_json = "*"
