[package]
name = "writus"
version = "0.1.0"
authors = ["PENGUINLIONG <admin@penguinliong.moe>"]

[dependencies]
chrono = "0.4.0"
iron = "0.5.1"
json = "0.11.8"
markdown = "0.2"
log = "0.3"
env_logger = "0.4"
